server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/toychip/Study.git
          default-label: master
          search-paths:
            - "스프링 Cloud로 개발하는 MSA"
            - "스프링 Cloud로 개발하는 MSA/spring-cloud-study-config.yml"